# Generated by Django 4.2.1 on 2023-06-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
        ('estudiantes', '0002_estudiantesmaterias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionesFinales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(verbose_name='Fecha de inscripción al final')),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiantes')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.materias')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionesCursadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(verbose_name='Fecha de inscripción')),
                ('curso', models.CharField(max_length=255, verbose_name='Curso')),
                ('division', models.CharField(max_length=255, verbose_name='División')),
                ('tipo_inscripcion', models.BooleanField(verbose_name='Regular o Libre')),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiantes')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.materias')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicosEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_cierre1', models.IntegerField(verbose_name='Primer nota')),
                ('nota_cierre2', models.IntegerField(verbose_name='Segunda nota')),
                ('porcentaje_asistencia', models.IntegerField(verbose_name='Porcentaje de asistencia')),
                ('resultado_cursada', models.BooleanField(verbose_name='Cursada aprobada')),
                ('final', models.IntegerField(verbose_name='Nota final')),
                ('fecha_final', models.DateField(verbose_name='Fecha del final')),
                ('tomo', models.CharField(max_length=255, verbose_name='Tomo')),
                ('folio', models.CharField(max_length=255, verbose_name='Folio')),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiantes')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.materias')),
            ],
        ),
    ]
