# Generated by Django 4.2.1 on 2023-06-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
