# Generated by Django 4.2.1 on 2023-06-03 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=255, verbose_name='Sexo')),
                ('nacionalidad', models.CharField(max_length=255, verbose_name='Nacionalidad')),
                ('secundario', models.CharField(max_length=255, verbose_name='Título otorgado por el nivel secundario')),
                ('ano_egreso_secundario', models.IntegerField(verbose_name='Año de egreso del nivel secundario')),
                ('domicilio', models.CharField(max_length=255, verbose_name='Domicilio')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('codigo_postal', models.CharField(max_length=255, verbose_name='Código Postal')),
                ('localidad', models.CharField(max_length=255, verbose_name='Localidad')),
                ('partido', models.CharField(max_length=255, verbose_name='Partido')),
                ('provincia', models.CharField(max_length=255, verbose_name='Provincia')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Dato del estudiante',
                'verbose_name_plural': 'Datos de los estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=255, unique=True, verbose_name='DNI')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('celular', models.CharField(max_length=255, verbose_name='Teléfono celular')),
                ('correo', models.CharField(max_length=255, verbose_name='Correo electrónico')),
                ('datos_estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.datosestudiantes')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['-dni'],
            },
        ),
    ]
