# Generated by Django 4.2.1 on 2023-06-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEstudiantes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('secundario', models.CharField(max_length=255)),
                ('ano_egreso_secundario', models.IntegerField()),
                ('domicilio', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('partido', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=255, unique=True)),
                ('apellido', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('datos_estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.datosestudiantes')),
            ],
        ),
    ]
