# Generated by Django 4.2.1 on 2023-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'ordering': ['-dni'], 'verbose_name': 'estudiante', 'verbose_name_plural': 'estudiantes'},
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
