# Generated by Django 4.2.1 on 2023-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_estudiantes_options_alter_datosestudiantes_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosestudiantes',
            options={'verbose_name': 'Dato del estudiante', 'verbose_name_plural': 'Datos de los estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'ordering': ['-dni'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='ano_egreso_secundario',
            field=models.IntegerField(verbose_name='Año de egreso del nivel secundario'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='codigo_postal',
            field=models.CharField(max_length=255, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='domicilio',
            field=models.CharField(max_length=255, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='localidad',
            field=models.CharField(max_length=255, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='nacionalidad',
            field=models.CharField(max_length=255, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='numero',
            field=models.CharField(max_length=255, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='partido',
            field=models.CharField(max_length=255, verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='provincia',
            field=models.CharField(max_length=255, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='secundario',
            field=models.CharField(max_length=255, verbose_name='Título otorgado por el nivel secundario'),
        ),
        migrations.AlterField(
            model_name='datosestudiantes',
            name='sexo',
            field=models.CharField(max_length=255, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='apellido',
            field=models.CharField(max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='celular',
            field=models.CharField(max_length=255, verbose_name='Teléfono celular'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='correo',
            field=models.CharField(max_length=255, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='dni',
            field=models.CharField(max_length=255, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
