# Generated by Django 4.2.1 on 2023-06-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('resolucion', models.CharField(max_length=255, verbose_name='Número de Resolución')),
                ('titulacion', models.CharField(max_length=255, verbose_name='Título que otorga')),
                ('duracion', models.CharField(max_length=255, verbose_name='Duración del Plan de Estudios')),
                ('cantidad_materias', models.CharField(max_length=255, verbose_name='Cantidad de materias')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('carga_horaria_semanal', models.IntegerField(verbose_name='Horas semanales')),
                ('carga_horaria_anual', models.IntegerField(verbose_name='Horas anuales')),
                ('es_cuatrimestral', models.BooleanField()),
                ('tipo_campo', models.CharField(max_length=255, verbose_name='Pertenece al campo de')),
                ('cantidad_correlativa', models.IntegerField(verbose_name='Cantidad de materias correlativas')),
                ('carreras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carreras')),
                ('correlativas', models.ManyToManyField(blank=True, to='carreras.materias')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['-id'],
            },
        ),
    ]
