# Generated by Django 4.2.1 on 2023-06-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesProfesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=255, verbose_name='Sexo')),
                ('nacionalidad', models.CharField(max_length=255, verbose_name='Nacionalidad')),
                ('titulo_base', models.CharField(max_length=255, verbose_name='Título de base')),
                ('ano_egreso', models.IntegerField(verbose_name='Año de egreso')),
                ('tramo_pedagogico', models.BooleanField(verbose_name='Posee tramo pedagógico')),
                ('domicilio', models.CharField(max_length=255, verbose_name='Domicilio')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('codigo_postal', models.CharField(max_length=255, verbose_name='Código postal')),
                ('localidad', models.CharField(max_length=255, verbose_name='Localidad')),
                ('partido', models.CharField(max_length=255, verbose_name='Partido')),
                ('provincia', models.CharField(max_length=255, verbose_name='Provincia')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=255, unique=True, verbose_name='DNI')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('celular', models.CharField(max_length=255, verbose_name='Celular')),
                ('correo', models.CharField(max_length=255, verbose_name='Correo particular')),
                ('correo_abc', models.CharField(max_length=255, verbose_name='Correo ABC')),
                ('detalles_profesores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.detallesprofesores')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesoresMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.materias')),
                ('profesores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.profesores')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profesoresmaterias',
            constraint=models.UniqueConstraint(fields=('profesores', 'materias'), name='unique_profesores_materias'),
        ),
    ]
